### ISSUE TITLE
We need to skype and finish agile stories

### ISSUE THREAD

**Issue by AnthonyKoutroulis** [FourMen/bulk-club#2]
Add your skype names:
anthony.koutroulis

**Comment by AnthonyKoutroulis** [comment]
Krystine showed me some example agile stories and they are broken up as:
Header: As a [someone] ... (short 'nonprogrammy' sentence describing feature)
Details: (specific 'programmy' implementation tasks and details) (listed details)
Done: (done requirements (listed))

Also that waffle.io is awesome and free, it works with the git issue tracker real nice.

**Comment by GoldHorizon** [comment]
Alright, my Skype username is:
nicholas.francke

I'll take a look at waffle.io too

**Comment by datowlcs** [comment]
Hey it's Nolan. Sorry for the late reply to this, but my skype is dat_owl_

I'll be ready in the next 5-10 minutes as well.

**Comment by ValkonX11** [comment]
Realized I forgot to put my skype name here. It should be either valkon or valkonx11, most likely the latter.
